### ISSUE TITLE
Create task_1_Prob_theory_and_math_statistics.ipynb

### ISSUE THREAD

**Issue by rudolfxcp** [alex-sokolov2011/mathematics#1]
Если перебрасывать только после 1 и 2, то матожидание 3.75 => вариантов исходов (1+2)*2/16 + (3+4+5+6)*3/16=3.75

**Comment by alex-sokolov2011** [comment]
Спасибо большое
Исправил

пт, 24 сент. 2021 г. в 17:31, rudolfxcp ***@***.***>:

**Comment by alex-sokolov2011** [comment]
close
